# createDevices.py creates a json file with devices for use in AT&T M2X system

import json

# Create a dictionary for each device, and add it to the list below. Include the phone number
# to text when an alarm is received, if enabled
# The parser name gets looked up in rest2m2x.py. If it is new, you need to add it
# in rest2m2x.py as well.
# NOTE: to send a text to a cellphone, use this as the email address: Ten_digit_number@X,
# X = vtext.com (verizon), text.att.net (att), tmomail.net (tmobile), messaging.sprintpcs.com (sprint)
# ex. ['8585551212@text.att.net']

devices = [

{'desc':'rACM Kit 1',
'nodeId':'0x00056a3b',
'parser':'temperature_humidity_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 2',
'nodeId':'0x00056a37',
'parser':'temperature_humidity_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 3',
'nodeId':'0x00056a36',
'parser':'temperature_humidity_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 4',
'nodeId':'0x00056a3f',
'parser':'temperature_humidity_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 5',
'nodeId':'0x00056aa5',
'parser':'serial_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 6',
'nodeId':'0x000347d3',
'parser':'serial_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 7',
'nodeId':'0x0003465a',
'parser':'serial_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 8',
'nodeId':'0x0003325c',
'parser':'serial_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 9',
'nodeId':'0x0003439a',
'parser':'serial_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 10',
'nodeId':'0x000348b1',
'parser':'serial_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 11',
'nodeId':'0x000348dd',
'parser':'serial_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 12',
'nodeId':'0x000348c8',
'parser':'serial_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 13',
'nodeId':'0x0003480f',
'parser':'serial_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 14',
'nodeId':'0x000343cb',
'parser':'serial_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 15',
'nodeId':'0x000569d7',
'parser':'intrusion_detector_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 16',
'nodeId':'0x00056a73',
'parser':'intrusion_detector_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 17',
'nodeId':'0x00056a74',
'parser':'intrusion_detector_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 18',
'nodeId':'0x00056a38',
'parser':'intrusion_detector_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 19',
'nodeId':'0x000569dd',
'parser':'intrusion_detector_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 20',
'nodeId':'0x00056aac',
'parser':'intrusion_detector_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 21',
'nodeId':'0x00032a0f',
'parser':'intrusion_detector_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 22',
'nodeId':'0x0005698c',
'parser':'intrusion_detector_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 23',
'nodeId':'0x000569de',
'parser':'intrusion_detector_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 24',
'nodeId':'0x000569ce',
'parser':'intrusion_detector_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 25',
'nodeId':'0x00034472',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 26',
'nodeId':'0x000347a3',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 27',
'nodeId':'0x00034396',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 28',
'nodeId':'0x000348ce',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 29',
'nodeId':'0x000348d9',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 30',
'nodeId':'0x00034343',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 31',
'nodeId':'0x0003451f',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 32',
'nodeId':'0x000348ad',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 33',
'nodeId':'0x000347fa',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 34',
'nodeId':'0x00034807',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 35',
'nodeId':'0x000348ac',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 36',
'nodeId':'0x000348e4',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 37',
'nodeId':'0x0003448c',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 38',
'nodeId':'0x000348f0',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 39',
'nodeId':'0x00034395',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 40',
'nodeId':'0x000346d6',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

{'desc':'rACM Kit 41',
'nodeId':'0x000347af',
'parser':'pulse_1',
'm2x_device_id': '',
'm2x_primary_key':'', 
'alarm_email_enabled':0,
'alarm_email_list':[]},

]

with open('ATT_Devices.json', 'w') as outfile:
   json.dump(devices, outfile)

print "create_devices: Done"
